### ISSUE TITLE
Uncaught TypeError: $(...).datetimepicker is not a function

### ISSUE THREAD

**Issue by taciomedeiros** [Haixing-Hu/vue-datetime-picker#13]
when use with browserify 

Uncaught TypeError: $(...).datetimepicker is not a function

**Comment by bitspintech** [comment]
Make sure you include jquery and datetimepicker before the vue component.

**Comment by Haixing-Hu** [comment]
You should include JQuery and datetime-picker.  Please refer to the demo page.
