### ISSUE TITLE
无法使用，Attributes "name", ":model.sync", ":on-change" are ignored on component <vue-datetime-picker> because the component is a fragment instance

### ISSUE THREAD

**Issue by js5323** [Haixing-Hu/vue-datetime-picker#14]
无法使用组件，无法传递数据
>[Vue warn]: Attributes "name", ":model.sync", ":on-change" are ignored on component <vue-datetime-picker> because the component is a fragment instance

**Comment by bitspintech** [comment]
line 193 	      
  langauge = DEFAULT_LANGUAGE;
Should be:
language = DEFAULT_LANGUAGE;

**Comment by roblav96** [comment]
anyone know how to fix this?

**Comment by loranger** [comment]
@roblav96 Define a language on your component :
```vue
<vue-datetime-picker ... language="en"></vue-datetime-picker>
```

**Comment by Haixing-Hu** [comment]
😓  That's my fault. I have fixed the typo error. And I should add a unit test to cover the case, if I have time ....

**Comment by Jono20201** [comment]
@Haixing-Hu It appears NPM hasn't picked up the new version?
