### ISSUE TITLE
Time format not working with Vuejs 1.0.10

### ISSUE THREAD

**Issue by neeravp** [Haixing-Hu/vue-datetime-picker#2]
I am trying to use with Vue1.0.10, but I am not able to get the time format right. I am getting control to show hours:mins:sec even if I set the type="time" and format="LT". I am not getting the AM/PM toggle. Also when I set the type to time, it still displays the calendar icon instead of clock.  
Can you please point me in the right direction as to how to get the clock icon as well as the AM/PM toggle button in the control.  
Thanks

**Comment by Haixing-Hu** [comment]
It has been upgrade to Vue.js v1.0.x.
