### ISSUE TITLE
Template or render function not defined.

### ISSUE THREAD

**Issue by pkimtani** [Haixing-Hu/vue-datetime-picker#39]
I installed the component as described in the doc

and used it this way inside a component:

    import VueDateTimePicker from 'vue-datetime-picker' 
    
    export default {
        name: "interaction-details",
        components: {
            VueDateTimePicker
        }
    }

HTML:
`<vue-date-time-picker/>`

But I am getting an error "Template or render function not defined"
I tried using the component at global level as well but still the same error.

Can someone help me if I am doing something wrong here?

**Comment by LiFaytheGoblin** [comment]
I have the same problem.

**Comment by fabiankaimer** [comment]
Me too.

**Comment by odera89** [comment]
Mee too :(

**Comment by joacimjakobsen** [comment]
Getting the same error here. 

In my case html is not `<vue-date-time-picker/>` but `<vue-datetime-picker>`

**Comment by LiensHuang** [comment]
me too

**Comment by tuvshinbatgeru** [comment]
I think this library is not for vue 2.*.

**Comment by imkimchi** [comment]
Anybody resolved this issue?

**Comment by fabiankaimer** [comment]
As AkilLis mentioned, this component doesn't seem to work with Vue.js 2.x and it also seems as it is not supported by the developer anymore. I am using "vue-bootstrap-datetimepicker" (https://github.com/ankurk91/vue-bootstrap-datetimepicker) instead. Works perfectly fine for me :)
