### ISSUE TITLE
TypeError: Path must be a string. Received [ 'src/vue-datetime-picker.js' ]

### ISSUE THREAD

**Issue by mhnrcjgs** [Haixing-Hu/vue-datetime-picker#5]
i tried to import it but i got this error. I'm still new with browserify and vue so this might me a minor issue. i need help. tnx.

var vm = new Vue({
    el: "#app",
    components: {
        "vue-datetime-picker": require('vue-datetime-picker')
    },

this is the error when i run gulp
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received [ 'src/vue-datetime-picker.js' ]
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:184:7)
    at D:\path\node_modules\resolve\lib\async.js:151:37
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)

**Comment by dandruff123** [comment]
I've received the same error, any thought or solutions how these can be solved ??

**Comment by 74sharlock** [comment]
@dandruff123 find <b>package.json</b>, and change the <b>"main"</b> field to string type. There are other problems with this component, Source code has been inconsistent with current version of the datetimepicker plugin.https://github.com/smalot/bootstrap-datetimepicker

**Comment by 74sharlock** [comment]
@dandruff123 ok, i wrote a very simple dateTimePicker component, like this:
``` javascript
let options = {
  useCurrent: false,
  showClear: true,
  showClose: false,
  minView: 2,
  fontAwesome: true,
  format: 'yyyy/m/d',
  autoclose: true,
  language: 'zh-CN'
};

export default Vue.component('datePicker', {
  replace: true,
  inherit: false,
  template: `<div class='input-group date'>
                <input class='form-control' v-model='model' type='text' readonly>
                <span class='input-group-addon'>
                  <i class='fa fa-fw fa-calendar'></i>
                </span>
             </div>`,
  props: ['model'],
  ready: function() {
    $(this.$el).datetimepicker(options);
  }
});

```
this is html:
```html
<date-picker :model.sync="queryDate" type="date"></date-picker>
```

use <b>Vue#1.0.21</b>
&& don't forget the <b>datetimepicker</b> plugin!

**Comment by Chalkin** [comment]
same problem when requiring the component in:

`require('vue-datetime-picker');`

> path.js:8
>     throw new TypeError('Path must be a string. Received ' +
>     ^
> 
> TypeError: Path must be a string. Received [ 'src/vue-datetime-picker.js' ]
>     at assertPath (path.js:8:11)
>     at Object.posix.resolve (path.js:426:5)
>     at /Users/patrick/Sites/_webseiten/freelance-portal/spark/node_modules/resolve/lib/async.js:151:37
>     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
>

**Comment by apstyx** [comment]
It is not pretty but it works for me 

"vue-datetime-picker": require("vue-datetime-picker/src/vue-datetime-picker.js")

**Comment by Haixing-Hu** [comment]
It has been fixed in the last release.
